project:
  type: website

website:
  title: "Trevor Thrash"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/trevorwthrash
      - icon: twitter
        href: https://twitter.com/trevorthrash
format:
  html:
    theme: cosmo
    css: styles.css



